// <auto-generated />
using System;
using BusSystemConsole.Contex;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusSystemConsole.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BusSystemConsole.Models.Onibus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("EntradaTerminal")
                        .HasColumnType("DATETIME")
                        .HasColumnName("entrada");

                    b.Property<string>("Motorista")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("motorista");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(7)")
                        .HasColumnName("placa");

                    b.Property<DateTime?>("SaidaTerminal")
                        .HasColumnType("DATETIME")
                        .HasColumnName("saida");

                    b.Property<int?>("TerminalId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.ToTable("onibus", (string)null);
                });

            modelBuilder.Entity("BusSystemConsole.Models.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome");

                    b.Property<int>("Vagas")
                        .HasColumnType("INT")
                        .HasColumnName("vagas");

                    b.HasKey("Id");

                    b.ToTable("Terminal", (string)null);
                });

            modelBuilder.Entity("BusSystemConsole.Models.Onibus", b =>
                {
                    b.HasOne("BusSystemConsole.Models.Terminal", "Terminal")
                        .WithMany("Onibus")
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("BusSystemConsole.Models.Terminal", b =>
                {
                    b.Navigation("Onibus");
                });
#pragma warning restore 612, 618
        }
    }
}
